// <auto-generated />
using System;
using CoffeeSpace.PaymentService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeSpace.PaymentService.Persistence.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeSpace.PaymentService.Application.Models.PaypalOrderInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaypalOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PaypalOrderId")
                        .IsUnique();

                    b.ToTable("Paypal Orders", (string)null);
                });

            modelBuilder.Entity("PayPalCheckoutSdk.Orders.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CheckoutPaymentIntent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreateTime")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("ExpirationTime")
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdateTime")
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("PayPalCheckoutSdk.Orders.PurchaseUnit", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("SoftDescriptor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("PurchaseUnits", (string)null);
                });

            modelBuilder.Entity("CoffeeSpace.PaymentService.Application.Models.PaypalOrderInformation", b =>
                {
                    b.HasOne("PayPalCheckoutSdk.Orders.Order", "PaypalOrder")
                        .WithOne()
                        .HasForeignKey("CoffeeSpace.PaymentService.Application.Models.PaypalOrderInformation", "PaypalOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaypalOrder");
                });

            modelBuilder.Entity("PayPalCheckoutSdk.Orders.PurchaseUnit", b =>
                {
                    b.HasOne("PayPalCheckoutSdk.Orders.Order", null)
                        .WithMany("PurchaseUnits")
                        .HasForeignKey("OrderId");

                    b.OwnsMany("PayPalCheckoutSdk.Orders.PurchaseUnit.Items#PayPalCheckoutSdk.Orders.Item", "Items", b1 =>
                        {
                            b1.Property<string>("PurchaseUnitId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(250)
                                .IsUnicode(false)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Quantity")
                                .IsRequired()
                                .IsUnicode(false)
                                .HasColumnType("text");

                            b1.Property<string>("UnitAmount")
                                .IsRequired()
                                .IsUnicode(false)
                                .HasColumnType("text");

                            b1.HasKey("PurchaseUnitId", "Id");

                            b1.ToTable("Items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PurchaseUnitId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("PayPalCheckoutSdk.Orders.Order", b =>
                {
                    b.Navigation("PurchaseUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
