apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      name: 'kafka'
      port: 9092
      targetPort: 9092
    - protocol: TCP
      name: 'controller'
      port: 9094
      targetPort: 9094
  type: LoadBalancer
  