apiVersion: v1
kind: Service
metadata:
  name: {{ include "ShipmentService.name" .}}
  namespace: {{ include "CoffeeSpace.namespace" .}}
  labels:
    {{- include "ShipmentService.labels" . | nindent 4}}
spec:
  selector:
    {{- include "ShipmentService.selectorLabels" . | nindent 8}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
