apiVersion: v1
kind: Service
metadata:
  name: {{ include "ApiGateway.name" .}}
  namespace: {{ include "CoffeeSpace.namespace" .}}
  labels:
    {{- include "ApiGateway.labels" . | nindent 4}}
spec:
  selector:
    {{- include "ApiGateway.selectorLabels" . | nindent 8}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
